name: generate-java-doc

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: get-files
        uses: actions/checkout@v3

      - name: install-java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: create-site
        run: mvn javadoc:javadoc

      - name: push-to-branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs/

        permissions:
          contents: write
