name: tests_on_push
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: get-files
        uses: actions/checkout@v3
      - name: install-java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: execute-tests
        run: mvn test
